# When you published a release, this action will run.
name: Publish packages

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm ci
          npm run build
      - name: Preview package contents
        run: npm pack --dry-run
      - name: Pack npm tarball
        id: pack
        run: |
          TARBALL=$(npm pack --silent)
          echo "tarball=$TARBALL" >> "$GITHUB_OUTPUT"
      - name: Upload tarball
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: package-tarball
          if-no-files-found: error
          path: ${{ steps.pack.outputs.tarball }}
  deploy:
    needs: build
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Download tarball
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 #v7.0.0
        with:
          name: package-tarball
          path: .
      # publish for npm package.
      - run: npm publish *.tgz --provenance --access public
      # publish for GitHub Package.
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tkskto'
      - run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
